import "@/styles/main.scss";

import { Providers } from "./providers";
import { Footer, Header } from "@/components/layout";

import type { Metadata } from "next";
import type { RootLayoutProps } from "./types";

export const metadata: Metadata = {
    title: "Create Appx App",
    description: "Generated by create appx app",
};

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Header />
                    {children}
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
